### ISSUE TITLE
Cannot override the parent style.

### ISSUE THREAD

**Issue by LM450N** [filaraujo/akyral-modal#12]
I have a component who extends the `akyral-modal`. It has a property `message` who contains a code, title and the content of the message to display. I only defined a default template used when the parent property `shown` is true. I would like to set the overlay background in red instead of dark gray but it doesn't work. How can I do that ?

**Comment by filaraujo** [comment]
At this time you can't update the background from within the extended component. I plan on updating it soon to support that. 

Hower you can style the element akyral-modal[core] from outside

#example
```css
akyral-modal[core] {
   background: red !important;
}
```

If you need even more control you can use :after and :before pseudo selectors to modify the core element.

```css
akyral-modal[core] {
  background: transparent;

  &:before {
    background: red;
    bottom: 0;
    content: '';
    left: 0;
    position: absolute;
    opacity: .8;
    right: 0;
    top: 0;
  }
}
```
This does the same thing as the top code, but gives you another 2 elements you can style
